apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
spec:
  type: LoadBalancer   # Use NodePort if running locally
  selector:
    app: netflix-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
